global:
  slack_api_url: <%= node[:secrets][:kmc_slack_wh_uri] %>

route:
  receiver: slack-notifications
  repeat_interval: 1h

receivers:
- name: slack-notifications
  slack_configs:
  - channel: '#nona-kanshi'
    send_resolved: true
    title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
