groups:
  - name: co2
    rules:
      - alert: high co2
        expr: udco2s_CO2{job="ud_cos2"} > 700
        for: 1m
        annotations:
          summary: CO2濃度高すぎ！
          description: "換気をしましょう。現在の濃度: {{ $value }}ppm"
      - alert: monitoring stopped
        expr: time() - udco2s_CO2{job="udco2s_last"} > 1800
        for: 1m
        annotations:
          summary: CO2モニタリング停止
          description: "CO2モニタリングが停止しています。"
      - alert: ValueHundredsChanged
        expr: floor(udco2s_CO2{job="ud_cos2"} / 100) != floor(udco2s_CO2{job="ud_cos2"} / 100 offset 1m)
        for: 0m
        labels:
          severity: info
        annotations:
          summary: CO2濃度お知らせ
          description: "現在の濃度: {{ udco2s_CO2{job="ud_cos2"} }}ppm"
