name: clouddns apply
on:
  push:
    branches:
      - master

jobs:
  apply:
    name: apply iii
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '204148502022/locations/global/workloadIdentityPools/dark-kuins-net-infra-github-wf/providers/dark-kuins-net-infra-github-wf'
          service_account: 'dark-kuins-net-infra-github-wf@united-crane-800.iam.gserviceaccount.com'
      - name: default login
        run: gcloud auth login --brief --cred-file=${{ steps.auth.outputs.credentials_file_path }}
      - name: bundle install
        run: bundle install
        working-directory: gcp/clouddns
      - name: apply
        run: bundle exec ruby main.rb
        working-directory: gcp/clouddns
